use_shaman: true
archive_upload_key: teuthology/openstack/archive-key
archive: /home/ubuntu/archive
archive_base: /home/ubuntu/archive
lock_server: http://localhost:8080/
results_server: http://localhost:8080/
gitbuilder_host: gitbuilder.ceph.com
check_package_signatures: false
ceph_git_url: https://github.com/ceph/ceph
queue_port: 11300
suite_verify_ceph_hash: false
queue_host: localhost
lab_domain: <domain_name>
max_job_time: 32400 # 9 hours
teuthology_path: .
teuthology_branch:main
teuthology_git_url: https://github.com/ceph/teuthology
canonical_tags: true
ssh_key: /home/ubuntu/cephkey
key_filename: /home/ubuntu/cephkey
ceph_cm_ansible_git_url: https://github.com/ceph/ceph-cm-ansible.git
vars:
  ansible_ssh_private_key_file: /home/ubuntu/ceph_id_rsa
openstack:
  key_filename: /home/ubuntu/cephkey
  clone: git clone http://github.com/ceph/teuthology
  user-data: teuthology/openstack/openstack-{os_type}-{os_version}-user-data.txt 
  ip: <host_ip>
  nameserver: <host_ip>
  keypair: cephkey
  selfname: teuthology
  server_name: teuth-teuthology
  server_group: teuth-teuthology
  worker_group: teuth-teuthology-worker
  package_repo: teuth-teuthology-repo
  machine:
    disk: 80 # GB
    ram: 16384 # MB
    cpus: 8
  volumes:
    count: 3
    size: 30 # GB
  flavor: <flavor>
  subnet: <subnet>
  network: <network_name>
  teardown: true